### ISSUE TITLE
トークンビュワーと異なる形態素解析が行われる文があります

### ISSUE THREAD

**Issue by ttrace** [textlint-ja/textlint-rule-morpheme-match#8]
トークンビュワーで「行列になったらしい。」を解析すると「たらしい」は、形容詞の接尾語として解析されますが、現行のルールで解析すると、「た」「らしい」という二つの助動詞になります。

https://azu.github.io/morpheme-match/?text=行列になったらしい%E3%80%82
たらしい | 形容詞 | 接尾

[morpheme-match](https://github.com/azu/morpheme-match) では、トークンビュワーと同じ結果が出ましたが、これは、こちらのバージョンが古いからなのでしょうか。

**Comment by azu** [comment]
https://github.com/textlint-ja/textlint-rule-morpheme-match/blob/00b0f3d1ee745057993a7059703301e9d9314f60/package.json#L61
https://github.com/azu/morpheme-match/blob/865f76805fce5e7beacdd127191ef19c4c103917/website/package.json#L44

ルールとデモサイトで、形態素解析するライブラリのバージョンが異なるのが原因かもしれないですね。

**Comment by azu** [comment]
kuromojin 1.xはkuromoji 0.1.2を参照してしまって
kuromojin 2.x は kumoji 0.1.1 で固定したので、このズレが起きてしまったみたいです。

https://github.com/azu/kuromojin/issues/8
https://github.com/takuyaa/kuromoji.js/issues/23

0.1.2
https://takuyaa.github.io/kuromoji.js/demo/tokenize.html
0.1.1
https://7e32v.csb.app/

**Comment by azu** [comment]
> [Update to kuromoji.js 0.1.2: HELP WANTED 🙇 🆘 · Issue #8 · azu/kuromojin](https://github.com/azu/kuromojin/issues/8)

上記のIssueで内部的に使っているkuromojinを kuromojin@3 へとそれぞれアップデートしました。

- [Release v2.0.0 · textlint-ja/textlint-rule-morpheme-match](https://github.com/textlint-ja/textlint-rule-morpheme-match/releases/tag/v2.0.0)
- https://azu.github.io/morpheme-match/?text=%E8%A1%8C%E5%88%97%E3%81%AB%E3%81%AA%E3%81%A3%E3%81%9F%E3%82%89%E3%81%97%E3%81%84%E3%80%82 

どちらも同じバージョンを使うようになったので、結果が一致するようになったと思います。

**Comment by ttrace** [comment]
アップグレードしました。トークンビュワーで確認次第、報告いたします。
